# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: ha-violet
version: "0.0.0.1"
slug: violet
description: PoolDigital Violet
url: "https://github.com/Xerolux/ha-violet.git"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/xerolux/ha-violet"
