ARG BUILD_FROM
#FROM $BUILD_FROM

FROM python:3.11-slim

# Install Rust and Cargo
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl \
    && curl https://sh.rustup.rs -sSf | sh -s -- -y

# Set environment variables to configure Cargo
ENV PATH="/root/.cargo/bin:${PATH}" \
    CARGO_HOME="/root/.cargo"

WORKDIR /app

RUN pip install requests homeassistant

COPY . .

CMD [ "python", "./main.py" ]


