ARG BUILD_FROM
#FROM $BUILD_FROM

FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
#RUN pip install --no-cache-dir -r requirements.txt
RUN pip install requests homeassistant
COPY . .

CMD [ "python", "./main.py" ]

